### ISSUE TITLE
fast.wistia.com

### ISSUE THREAD

**Issue by p1r473** [DataMaster-2501/DataMaster-Android-AdBlock-Hosts#6] opened 2020-03-22 20:21 UTC
This domain is required for embedded videos on some sites
Eg.  purposeinvest.com/canadians uses this for embedded videos.

**Comment by DataMaster-2501** [comment] 2020-11-05 00:08
Duplicate of #20
The domain is not removed
end of line

**Closed as completed by DataMaster-2501** 2020-11-05 00:08 UTC
Labels: Bug, Won't Fix
